### ISSUE TITLE
Link can't be created in footer

### ISSUE THREAD

**Issue by mtancoigne** [el-cms/croogo-reports-plugin#2]
I don't know how to create a link wich handle custom attributes in  a menu : a "Report this page" button should be created in the footer or main menu, but I can't find anything on custom attributes (as data-toggle or other exotic attributes)

**Comment by rchavik** [comment]
Maybe [this](https://github.com/croogo/croogo/commit/b4e3d79aa2986efc7cca3b3ae292724442bcd8a0) can help.

See the second chunk on `testEmbeddedOptions()`
